let nodemailer;
try {
  nodemailer = require('nodemailer');
} catch (err) {
  nodemailer = null;
}

const IntegrationLog = require('../models/IntegrationLog');
const IntegrationConfig = require('../models/IntegrationConfig');
const config = require('../config/config');

class EmailService {
  constructor() {
    this.fromEmail = process.env.EMAIL_FROM || 'no-reply@aquafishingacademy.com';
    this.fromName = 'Aqua Fishing Academy ERP';
    this.smtpHost = process.env.SMTP_HOST || '';
    this.smtpPort = Number(process.env.SMTP_PORT) || 587;
    this.smtpUser = process.env.SMTP_USER || '';
    this.smtpPass = process.env.SMTP_PASSWORD || '';
    this.isConfigured = Boolean(this.smtpHost && this.smtpUser && nodemailer);

    if (this.isConfigured && nodemailer) {
      this.transporter = nodemailer.createTransport({
        host: this.smtpHost,
        port: this.smtpPort,
        secure: this.smtpPort === 465,
        auth: {
          user: this.smtpUser,
          pass: this.smtpPass,
        },
      });
    } else {
      this.transporter = null;
    }
  }

  /**
   * Escape HTML utility to prevent XSS injection in templates.
   */
  escapeHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  /**
   * Generates formatted branded HTML email template.
   */
  renderTemplate(templateName, data = {}) {
    const brandHeader = `
      <div style="background-color: #0c4a6e; padding: 24px; text-align: center; border-radius: 12px 12px 0 0;">
        <h1 style="color: #ffffff; margin: 0; font-family: sans-serif; font-size: 22px; font-weight: 800; letter-spacing: 1px;">
          AQUA FISHING ACADEMY
        </h1>
        <p style="color: #38bdf8; margin: 4px 0 0 0; font-size: 11px; text-transform: uppercase; letter-spacing: 2px;">
          Maritime Education &amp; Charter Excellence
        </p>
      </div>
    `;

    const brandFooter = `
      <div style="background-color: #f8fafc; padding: 20px; text-align: center; font-size: 11px; color: #64748b; border-radius: 0 0 12px 12px; border-top: 1px solid #e2e8f0;">
        <p style="margin: 0;">Aqua Fishing Academy LLC • Dubai &amp; Fujairah, United Arab Emirates</p>
        <p style="margin: 4px 0 0 0;">This is an automated operational notification generated by AFA ERP.</p>
      </div>
    `;

    let bodyContent = '';

    switch (templateName) {
      case 'bookingConfirmation':
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">Booking Confirmed!</h2>
          <p>Dear <strong>${this.escapeHtml(data.customerName)}</strong>,</p>
          <p>Your enrollment in <strong>${this.escapeHtml(data.programTitle)}</strong> has been successfully confirmed.</p>
          <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin: 20px 0;">
            <p style="margin: 0; color: #166534; font-size: 13px;"><strong>Booking Reference:</strong> ${this.escapeHtml(data.bookingNumber || data.bookingId)}</p>
            <p style="margin: 6px 0 0 0; color: #166534; font-size: 13px;"><strong>Branch Location:</strong> ${this.escapeHtml(data.branchName || 'Dubai Marina')}</p>
            <p style="margin: 6px 0 0 0; color: #166534; font-size: 13px;"><strong>Date &amp; Time:</strong> ${this.escapeHtml(data.sessionDate || 'Scheduled Session')}</p>
          </div>
          <p>Please arrive 15 minutes before departure with appropriate maritime attire.</p>
        `;
        break;

      case 'paymentReceipt':
        bodyContent = `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0f172a; max-width: 680px; margin: 0 auto; background: #ffffff; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px;">
            <!-- Header -->
            <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px;">
              <div>
                <h1 style="font-size: 28px; font-weight: 800; color: #0f172a; margin: 0;">Receipt</h1>
              </div>
            </div>

            <!-- Receipt Info -->
            <table style="width: 100%; font-size: 13px; margin-bottom: 24px; border-collapse: collapse;">
              <tr>
                <td style="width: 140px; color: #475569; padding: 3px 0;">Receipt number</td>
                <td style="font-weight: bold; color: #0f172a; padding: 3px 0;">${this.escapeHtml(data.receiptNumber)}</td>
              </tr>
              <tr>
                <td style="color: #475569; padding: 3px 0;">Invoice number</td>
                <td style="font-weight: bold; color: #0f172a; padding: 3px 0;">${this.escapeHtml(data.invoiceNumber)}</td>
              </tr>
              <tr>
                <td style="color: #475569; padding: 3px 0;">Date paid</td>
                <td style="color: #0f172a; padding: 3px 0;">${this.escapeHtml(data.paymentDate || new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }))}</td>
              </tr>
              <tr>
                <td style="color: #475569; padding: 3px 0;">Payment method</td>
                <td style="font-weight: bold; color: #0f172a; padding: 3px 0;">${this.escapeHtml(data.paymentMethod || 'Total Pay')}</td>
              </tr>
            </table>

            <!-- Bill From & Bill To -->
            <table style="width: 100%; font-size: 12px; margin-bottom: 30px; border-collapse: collapse;">
              <tr>
                <td style="width: 50%; vertical-align: top; padding-right: 15px;">
                  <div style="font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px;">BILL FROM</div>
                  <div style="font-weight: bold; color: #0f172a; font-size: 13px;">Aqua Fishing Academy</div>
                  <div style="color: #475569;">United Arab Emirates</div>
                  <div style="color: #475569;">+971 56 990 5688</div>
                  <div style="color: #475569;">info@aquafishingacademy.com</div>
                  <div style="color: #475569;">aquafishingacademy.com/</div>
                </td>
                <td style="width: 50%; vertical-align: top; padding-left: 15px;">
                  <div style="font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px;">BILL TO</div>
                  <div style="font-weight: bold; color: #0f172a; font-size: 13px;">${this.escapeHtml(data.parentName || data.customerName || data.recipientName)}</div>
                  ${data.customerPhone ? `<div style="color: #475569;">${this.escapeHtml(data.customerPhone)}</div>` : ''}
                  ${data.customerEmail ? `<div style="color: #475569;">${this.escapeHtml(data.customerEmail)}</div>` : ''}
                </td>
              </tr>
            </table>

            <!-- Large Payment Summary -->
            <div style="font-size: 22px; font-weight: 800; color: #0f172a; margin: 28px 0; border-top: 1px solid #f1f5f9; padding-top: 20px;">
              AED ${Number(data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Paid via ${this.escapeHtml(data.paymentMethod || 'Total Pay')} on ${this.escapeHtml(data.paymentDate || data.datePaid || new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }))}
            </div>

            <!-- Items Table -->
            <table style="width: 100%; font-size: 12px; border-collapse: collapse; margin-bottom: 24px;">
              <thead>
                <tr style="border-bottom: 2px solid #334155; text-align: left; font-size: 11px; color: #475569; text-transform: uppercase;">
                  <th style="padding: 8px 4px;">DESCRIPTION</th>
                  <th style="padding: 8px 4px; text-align: center; width: 50px;">QTY</th>
                  <th style="padding: 8px 4px; text-align: right; width: 100px;">UNIT PRICE</th>
                  <th style="padding: 8px 4px; text-align: right; width: 90px;">DISCOUNT</th>
                  <th style="padding: 8px 4px; text-align: right; width: 100px;">AMOUNT</th>
                </tr>
              </thead>
              <tbody>
                ${Array.isArray(data.lineItems) && data.lineItems.length > 0 ? (
                  data.lineItems.map(item => `
                    <tr style="border-bottom: 1px solid #e2e8f0;">
                      <td style="padding: 12px 4px; vertical-align: top;">
                        <div style="font-weight: bold; color: #0f172a; font-size: 13px;">${this.escapeHtml(item.item || item.description || data.programTitle || 'Academy Maritime Session')}</div>
                        ${item.description && item.item && item.description !== item.item ? `<div style="color: #475569; font-size: 11px; margin-top: 3px;">${this.escapeHtml(item.description)}</div>` : ''}
                        ${item.validity ? `<div style="color: #475569; font-size: 11px; margin-top: 3px;"><strong>Validity</strong> ${this.escapeHtml(item.validity)}</div>` : ''}
                      </td>
                      <td style="padding: 12px 4px; text-align: center; vertical-align: top; color: #0f172a;">${item.quantity || 1}</td>
                      <td style="padding: 12px 4px; text-align: right; vertical-align: top; color: #0f172a;">AED ${Number(item.unitPrice || item.amount || data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                      <td style="padding: 12px 4px; text-align: right; vertical-align: top; color: #0f172a;">AED ${Number(item.discount?.amount || item.discount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                      <td style="padding: 12px 4px; text-align: right; vertical-align: top; font-weight: bold; color: #0f172a;">AED ${Number(item.amount || data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                    </tr>
                  `).join('')
                ) : `
                  <tr style="border-bottom: 1px solid #e2e8f0;">
                    <td style="padding: 12px 4px; vertical-align: top;">
                      <div style="font-weight: bold; color: #0f172a; font-size: 13px;">${this.escapeHtml(data.programTitle || 'Academy Maritime Session')}</div>
                      ${data.sessionDate ? `<div style="color: #475569; font-size: 11px; margin-top: 3px;">${this.escapeHtml(data.sessionDate)}</div>` : ''}
                      ${data.validity ? `<div style="color: #475569; font-size: 11px; margin-top: 3px;"><strong>Validity</strong> ${this.escapeHtml(data.validity)}</div>` : ''}
                    </td>
                    <td style="padding: 12px 4px; text-align: center; vertical-align: top; color: #0f172a;">1</td>
                    <td style="padding: 12px 4px; text-align: right; vertical-align: top; color: #0f172a;">AED ${Number(data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                    <td style="padding: 12px 4px; text-align: right; vertical-align: top; color: #0f172a;">AED 0.00</td>
                    <td style="padding: 12px 4px; text-align: right; vertical-align: top; font-weight: bold; color: #0f172a;">AED ${Number(data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                  </tr>
                `}
              </tbody>
            </table>

            <!-- Totals -->
            <div style="display: flex; justify-content: flex-end; margin-bottom: 24px;">
              <table style="width: 260px; font-size: 12px; border-collapse: collapse; margin-left: auto;">
                <tr style="border-top: 1px solid #475569;">
                  <td style="padding: 6px 0; color: #475569;">Subtotal</td>
                  <td style="padding: 6px 0; text-align: right; color: #0f172a;">AED ${Number(data.subtotal || data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #475569;">Rounded off</td>
                  <td style="padding: 6px 0; text-align: right; color: #0f172a;">AED ${Number(data.roundingAdjustment || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
                <tr style="border-top: 1px solid #475569; border-bottom: 1px solid #475569;">
                  <td style="padding: 6px 0; color: #0f172a;">Total</td>
                  <td style="padding: 6px 0; text-align: right; color: #0f172a;">AED ${Number(data.totalAmount || data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">Paid</td>
                  <td style="padding: 8px 0; text-align: right; font-weight: bold; color: #0f172a;">- AED ${Number(data.paidAmount || data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
              </table>
            </div>

            <!-- Payments -->
            <div style="border-top: 1px solid #e2e8f0; padding-top: 16px;">
              <div style="font-weight: bold; font-size: 13px; color: #0f172a; margin-bottom: 4px;">Payments</div>
              <div style="font-size: 12px; color: #475569;">
                AED ${Number(data.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} payment via ${this.escapeHtml(data.paymentMethod || 'Total Pay')} on ${this.escapeHtml(data.paymentDate || data.datePaid || new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }))}
              </div>
            </div>
          </div>
        `;
        break;

      case 'invoiceIssued':
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">Invoice Issued — #${this.escapeHtml(data.invoiceNumber)}</h2>
          <p>Dear <strong>${this.escapeHtml(data.customerName)}</strong>,</p>
          <p>A new invoice for <strong>AED ${Number(data.totalAmount || 0).toLocaleString()}</strong> has been generated for your recent booking.</p>
          <div style="margin: 24px 0; text-align: center;">
            <a href="${data.paymentUrl || config.clientUrl}" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 8px; font-weight: bold; text-decoration: none; display: inline-block;">
              View &amp; Pay Invoice Online
            </a>
          </div>
        `;
        break;

      default:
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">${this.escapeHtml(data.title || 'Notification')}</h2>
          <p>${this.escapeHtml(data.message || '')}</p>
        `;
    }

    return `
      <!DOCTYPE html>
      <html>
      <body style="margin: 0; padding: 20px; background-color: #f1f5f9; font-family: sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
          ${brandHeader}
          <div style="padding: 30px; font-size: 14px; line-height: 1.6; color: #334155;">
            ${bodyContent}
          </div>
          ${brandFooter}
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Main email dispatch handler.
   */
  async sendEmail({ to, subject, template, data = {}, attachments = [] }) {
    const correlationId = crypto.randomUUID();
    const html = this.renderTemplate(template, data);

    if (!this.isConfigured || !this.transporter) {
      // Sandbox / Test Mode Dispatch Simulation
      const simulatedMsgId = `<simulated_${Date.now()}@aquafishingacademy.com>`;
      console.log(`[EmailService - Test Mode] Email "${subject}" simulated to ${to}`);

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.sent.simulated',
        direction: 'OUTBOUND',
        externalId: simulatedMsgId,
        status: 'SUCCESS',
        requestPayload: { to, subject, template, sandbox: true },
        responsePayload: { messageId: simulatedMsgId, status: 'simulated_delivery' },
      });

      return { success: true, messageId: simulatedMsgId, isSandbox: true };
    }

    try {
      const info = await this.transporter.sendMail({
        from: `"${this.fromName}" <${this.fromEmail}>`,
        to,
        subject,
        html,
        attachments,
      });

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.sent',
        direction: 'OUTBOUND',
        externalId: info.messageId,
        status: 'SUCCESS',
        requestPayload: { to, subject, template },
        responsePayload: { messageId: info.messageId, response: info.response },
      });

      await IntegrationConfig.findOneAndUpdate(
        { provider: 'email' },
        {
          $set: {
            lastSuccessfulSync: new Date(),
            status: 'CONNECTED',
          },
          $inc: { totalEventsProcessed: 1 },
        },
        { upsert: true }
      );

      return { success: true, messageId: info.messageId, isSandbox: false };
    } catch (err) {
      console.error('[EmailService] Dispatch failed:', err);

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.failed',
        direction: 'OUTBOUND',
        status: 'FAILED',
        errorMessage: err.message,
        requestPayload: { to, subject, template },
      });

      await IntegrationConfig.findOneAndUpdate(
        { provider: 'email' },
        {
          $set: {
            lastFailedSync: new Date(),
            lastError: err.message,
          },
          $inc: { totalErrors: 1 },
        },
        { upsert: true }
      );

      throw err;
    }
  }
}

module.exports = new EmailService();
