let nodemailer;
try {
  nodemailer = require('nodemailer');
} catch (err) {
  nodemailer = null;
}

const IntegrationLog = require('../models/IntegrationLog');
const IntegrationConfig = require('../models/IntegrationConfig');
const config = require('../config/config');

class EmailService {
  constructor() {
    this.fromEmail = process.env.EMAIL_FROM || 'no-reply@aquafishingacademy.com';
    this.fromName = 'Aqua Fishing Academy ERP';
    this.smtpHost = process.env.SMTP_HOST || '';
    this.smtpPort = Number(process.env.SMTP_PORT) || 587;
    this.smtpUser = process.env.SMTP_USER || '';
    this.smtpPass = process.env.SMTP_PASSWORD || '';
    this.isConfigured = Boolean(this.smtpHost && this.smtpUser && nodemailer);

    if (this.isConfigured && nodemailer) {
      this.transporter = nodemailer.createTransport({
        host: this.smtpHost,
        port: this.smtpPort,
        secure: this.smtpPort === 465,
        auth: {
          user: this.smtpUser,
          pass: this.smtpPass,
        },
      });
    } else {
      this.transporter = null;
    }
  }

  /**
   * Escape HTML utility to prevent XSS injection in templates.
   */
  escapeHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  /**
   * Generates formatted branded HTML email template.
   */
  renderTemplate(templateName, data = {}) {
    const brandHeader = `
      <div style="background-color: #0c4a6e; padding: 24px; text-align: center; border-radius: 12px 12px 0 0;">
        <h1 style="color: #ffffff; margin: 0; font-family: sans-serif; font-size: 22px; font-weight: 800; letter-spacing: 1px;">
          AQUA FISHING ACADEMY
        </h1>
        <p style="color: #38bdf8; margin: 4px 0 0 0; font-size: 11px; text-transform: uppercase; letter-spacing: 2px;">
          Maritime Education &amp; Charter Excellence
        </p>
      </div>
    `;

    const brandFooter = `
      <div style="background-color: #f8fafc; padding: 20px; text-align: center; font-size: 11px; color: #64748b; border-radius: 0 0 12px 12px; border-top: 1px solid #e2e8f0;">
        <p style="margin: 0;">Aqua Fishing Academy LLC • Dubai &amp; Fujairah, United Arab Emirates</p>
        <p style="margin: 4px 0 0 0;">This is an automated operational notification generated by AFA ERP.</p>
      </div>
    `;

    let bodyContent = '';

    switch (templateName) {
      case 'bookingConfirmation':
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">Booking Confirmed!</h2>
          <p>Dear <strong>${this.escapeHtml(data.customerName)}</strong>,</p>
          <p>Your enrollment in <strong>${this.escapeHtml(data.programTitle)}</strong> has been successfully confirmed.</p>
          <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin: 20px 0;">
            <p style="margin: 0; color: #166534; font-size: 13px;"><strong>Booking Reference:</strong> ${this.escapeHtml(data.bookingNumber || data.bookingId)}</p>
            <p style="margin: 6px 0 0 0; color: #166534; font-size: 13px;"><strong>Branch Location:</strong> ${this.escapeHtml(data.branchName || 'Dubai Marina')}</p>
            <p style="margin: 6px 0 0 0; color: #166534; font-size: 13px;"><strong>Date &amp; Time:</strong> ${this.escapeHtml(data.sessionDate || 'Scheduled Session')}</p>
          </div>
          <p>Please arrive 15 minutes before departure with appropriate maritime attire.</p>
        `;
        break;

      case 'paymentReceipt':
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 20px; margin-top: 0;">Official Payment Receipt</h2>
          <p style="font-size: 14px; color: #334155;">Dear <strong>${this.escapeHtml(data.recipientName || data.customerName)}</strong>,</p>
          <p style="font-size: 14px; color: #334155;">Thank you for your payment to <strong>Aqua Fishing Academy</strong>. Your transaction has been successfully processed and verified.</p>
          
          <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 18px; margin: 20px 0;">
            <table style="width: 100%; font-size: 13px; color: #334155; border-collapse: collapse;">
              <tr>
                <td style="padding: 5px 0; color: #64748b; width: 40%;"><strong>Receipt Number:</strong></td>
                <td style="padding: 5px 0; font-family: monospace; font-weight: bold; color: #0f172a;">${this.escapeHtml(data.receiptNumber)}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Invoice Reference:</strong></td>
                <td style="padding: 5px 0; font-family: monospace; font-weight: bold; color: #0284c7;">${this.escapeHtml(data.invoiceNumber)}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Student Name:</strong></td>
                <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${this.escapeHtml(data.studentName || data.customerName)}${data.studentCode ? ` (${this.escapeHtml(data.studentCode)})` : ''}</td>
              </tr>
              ${data.parentName && data.parentName !== data.studentName ? `
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Parent / Guardian:</strong></td>
                <td style="padding: 5px 0; color: #0f172a;">${this.escapeHtml(data.parentName)}</td>
              </tr>` : ''}
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Program / Class:</strong></td>
                <td style="padding: 5px 0; color: #0f172a;">${this.escapeHtml(data.programTitle || 'Academy Training')}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Branch Location:</strong></td>
                <td style="padding: 5px 0; color: #0f172a;">${this.escapeHtml(data.branchName || 'Dubai Marina')}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Payment Method:</strong></td>
                <td style="padding: 5px 0; color: #0f172a;">${this.escapeHtml(data.paymentMethod || 'Credit Card')}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Payment Date:</strong></td>
                <td style="padding: 5px 0; color: #0f172a;">${this.escapeHtml(data.paymentDate || new Date().toLocaleDateString('en-AE'))}</td>
              </tr>
              <tr style="border-top: 1px solid #e2e8f0;">
                <td style="padding: 10px 0 5px 0; color: #16a34a; font-size: 14px;"><strong>Amount Paid:</strong></td>
                <td style="padding: 10px 0 5px 0; font-size: 16px; font-weight: 800; color: #16a34a;">AED ${Number(data.amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; color: #64748b;"><strong>Remaining Balance Due:</strong></td>
                <td style="padding: 5px 0; font-weight: bold; color: ${Number(data.balanceDue) > 0 ? '#d97706' : '#64748b'};">AED ${Number(data.balanceDue || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
            </table>
          </div>
          
          <p style="font-size: 13px; color: #64748b; margin-top: 16px;">
            This receipt serves as official proof of payment. You can also view and download your full invoices and payment receipts anytime via the <a href="${config.clientUrl || 'https://aquafishinghub.com'}/finance/receipts" style="color: #0284c7; font-weight: bold; text-decoration: none;">Aqua Fishing Academy Portal</a>.
          </p>
        `;
        break;

      case 'invoiceIssued':
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">Invoice Issued — #${this.escapeHtml(data.invoiceNumber)}</h2>
          <p>Dear <strong>${this.escapeHtml(data.customerName)}</strong>,</p>
          <p>A new invoice for <strong>AED ${Number(data.totalAmount || 0).toLocaleString()}</strong> has been generated for your recent booking.</p>
          <div style="margin: 24px 0; text-align: center;">
            <a href="${data.paymentUrl || config.clientUrl}" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 8px; font-weight: bold; text-decoration: none; display: inline-block;">
              View &amp; Pay Invoice Online
            </a>
          </div>
        `;
        break;

      default:
        bodyContent = `
          <h2 style="color: #0f172a; font-size: 18px;">${this.escapeHtml(data.title || 'Notification')}</h2>
          <p>${this.escapeHtml(data.message || '')}</p>
        `;
    }

    return `
      <!DOCTYPE html>
      <html>
      <body style="margin: 0; padding: 20px; background-color: #f1f5f9; font-family: sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
          ${brandHeader}
          <div style="padding: 30px; font-size: 14px; line-height: 1.6; color: #334155;">
            ${bodyContent}
          </div>
          ${brandFooter}
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Main email dispatch handler.
   */
  async sendEmail({ to, subject, template, data = {}, attachments = [] }) {
    const correlationId = crypto.randomUUID();
    const html = this.renderTemplate(template, data);

    if (!this.isConfigured || !this.transporter) {
      // Sandbox / Test Mode Dispatch Simulation
      const simulatedMsgId = `<simulated_${Date.now()}@aquafishingacademy.com>`;
      console.log(`[EmailService - Test Mode] Email "${subject}" simulated to ${to}`);

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.sent.simulated',
        direction: 'OUTBOUND',
        externalId: simulatedMsgId,
        status: 'SUCCESS',
        requestPayload: { to, subject, template, sandbox: true },
        responsePayload: { messageId: simulatedMsgId, status: 'simulated_delivery' },
      });

      return { success: true, messageId: simulatedMsgId, isSandbox: true };
    }

    try {
      const info = await this.transporter.sendMail({
        from: `"${this.fromName}" <${this.fromEmail}>`,
        to,
        subject,
        html,
        attachments,
      });

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.sent',
        direction: 'OUTBOUND',
        externalId: info.messageId,
        status: 'SUCCESS',
        requestPayload: { to, subject, template },
        responsePayload: { messageId: info.messageId, response: info.response },
      });

      await IntegrationConfig.findOneAndUpdate(
        { provider: 'email' },
        {
          $set: {
            lastSuccessfulSync: new Date(),
            status: 'CONNECTED',
          },
          $inc: { totalEventsProcessed: 1 },
        },
        { upsert: true }
      );

      return { success: true, messageId: info.messageId, isSandbox: false };
    } catch (err) {
      console.error('[EmailService] Dispatch failed:', err);

      await IntegrationLog.create({
        correlationId,
        provider: 'email',
        event: 'email.failed',
        direction: 'OUTBOUND',
        status: 'FAILED',
        errorMessage: err.message,
        requestPayload: { to, subject, template },
      });

      await IntegrationConfig.findOneAndUpdate(
        { provider: 'email' },
        {
          $set: {
            lastFailedSync: new Date(),
            lastError: err.message,
          },
          $inc: { totalErrors: 1 },
        },
        { upsert: true }
      );

      throw err;
    }
  }
}

module.exports = new EmailService();
